title: Jaime Sparks # your name (or website title) here
logo: "/images/Sunrays.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Professional with 8+ years of project experience in analyzing data and providing insights to drive business solutions in various industries.
  Proficient knowledge in cleansing and appending data using VBA, Excel and basic SQL. Excellent understanding 
  of business operations and visualization tools for effective interpretation of data.
  <br><br>
  Currently positioning myself for future projects in Healthcare.   
  My primary focus is to transfer current skills and past experience while improving SQL and Cloud computing skills, as it relates to EHR data.
  
  
theme: jekyll-theme-minimal
google_analytics: UA-143535457-1 # your Google Analytics tracking ID here
