title: Jaime Sparks # your name (or website title) here
logo: "/images/Sunrays.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Solutions and Software Delopment  
  <br><br>  
  
theme: jekyll-theme-minimal
google_analytics: UA-143535457-1 # your Google Analytics tracking ID here
