title: Jaime Sparks # your name (or website title) here
logo: "/images/Sunrays.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Professional with 10+ years of project experience in analyzing data and providing insights to drive business solutions in various industries.
  Proficient knowledge in cleansing and appending data using VBA, Excel and basic SQL. Excellent understanding 
  of business operations and visualization tools for effective interpretation of data.
  <br><br>
  Positioning myself to pivot into future Risk and Healthcare projects.   
  My primary focus is to continuously grow and master new skills that complement past experiences while improving in SQL and Python.
  
  
theme: jekyll-theme-minimal
google_analytics: UA-143535457-1 # your Google Analytics tracking ID here
