title: Jaime Sparks # your name (or website title) here
logo: "/images/Sunrays.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Professional with 8+ years of experience in interpreting and analyzing data for driving business solutions.
  Proficient knowledge in cleaning and appending data using VBA and Excel. Excellent understanding 
  of business operations and visualization tools for effective analyses of data.
  <br><br>
  Currently working on a project to create a Baseline Inventory of External Third Parties for a international client. 
  My primary focus is to utilize previous experience while improving automation and UI design skills.
  <br><br>
  
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
